import numpy as np
from DiscreteD import DiscreteD
from GaussD import GaussD
#from MarkovChain import MarkovChain


class HMM:
    """
    HMM - class for Hidden Markov Models, representing
    statistical properties of random sequences.
    Each sample in the sequence is a scalar or vector, with fixed DataSize.
    
    Several HMM objects may be collected in a single multidimensional array.
    
    A HMM represents a random sequence(X1,X2,....Xt,...),
    where each element Xt can be a scalar or column vector.
    The statistical dependence along the (time) sequence is described
    entirely by a discrete Markov chain.
    
    A HMM consists of two sub-objects:
    1: a State Sequence Generator of type MarkovChain
    2: an array of output probability distributions, one for each state
    
    All states must have the same class of output distribution,
    such as GaussD, GaussMixD, or DiscreteD, etc.,
    and the set of distributions is represented by an object array of that class,
    although this is NOT required by general HMM theory.
    
    All output distributions must have identical DataSize property values.
    
    Any HMM output sequence X(t) is determined by a hidden state sequence S(t)
    generated by an internal Markov chain.
    
    The array of output probability distributions, with one element for each state,
    determines the conditional probability (density) P[X(t) | S(t)].
    Given S(t), each X(t) is independent of all other X(:).
    
    
    References:
    Leijon, A. (20xx) Pattern Recognition. KTH, Stockholm.
    Rabiner, L. R. (1989) A tutorial on hidden Markov models
    	and selected applications in speech recognition.
    	Proc IEEE 77, 257-286.
    
    """
    def __init__(self, mc, distributions):

        self.stateGen = mc
        self.outputDistr = distributions

        self.nStates = mc.nStates
        self.dataSize = distributions[0].dataSize
    
    def rand(self, nSamples):
        """
        [X,S]=rand(self,nSamples); generates a random sequence of data
        from a given Hidden Markov Model.
        
        Input:
        nSamples=  maximum no of output samples (scalars or column vectors)
        
        Result:
        X= matrix or row vector with output data samples
        S= row vector with corresponding integer state values
          obtained from the self.StateGen component.
          nS= length(S) == size(X,2)= number of output samples.
          If the StateGen can generate infinite-duration sequences,
              nS == nSamples
          If the StateGen is a finite-duration MarkovChain,
              nS <= nSamples
        """
        S = self.stateGen.rand(nSamples)
        #For scalar observations
        if self.outputDistr[0].dataSize == 1:
            X = np.zeros(len(S))
        #For vector observations
        else:
            #X = np.zeros((self.outputDistr[0].dataSize, len(S)))
            X = np.zeros((len(S), self.outputDistr[0].dataSize))
        
        #Generate observations for each state in the sequence
        for i, state in enumerate(S):
            #Select the distribution corresponding to the current state
            distr = self.outputDistr[state - 1]  #Adjusting index for 0-based Python indexing
            
            #Generate a random observation from the distribution
            """print("X_shape ", X.shape)
            print("rand1 ", distr.rand(1))
            print("rand2 ",distr.rand(2))"""
            X[i] = distr.rand(1).flatten() 
        return X, S
        
    def viterbi(self):
        pass

    def train(self):
        pass

    def stateEntropyRate(self):
        pass

    def setStationary(self):
        pass

    def logprob(self, pX, scale_factors):
        alpha, c = self.stateGen.forward(pX)
        logprob = np.sum(np.log(c))
        logP = logprob + np.sum(np.log(scale_factors))
        return logP

    def adaptStart(self):
        pass

    def adaptSet(self):
        pass

    def adaptAccum(self):
        pass
    def updateq(self, alpha, beta, c):
        """alpha Forward probabilities, shape (N, T) where N is number of states, T is number of time steps
        beta  Backward probabilities, shape (N, T)
        c Scaling factors for each time step, shape (T,)"""
        alpha_0 = alpha[:, 0]  # Forward probabilities for all states at time 1
        beta_0 = beta[:, 0]    # Backward probabilities for all states at time 1
        c_0 = c[0]             # Scaling factor at the first time step

        # Calculate the updated initial probabilities
        new_q = (alpha_0 * beta_0) / c_0

        # Normalize new_q to ensure it sums to 1
        new_q = (new_q / np.sum(new_q))
        
        # Update the model's initial state probabilities
        self.stateGen.q = new_q

    def updateA(self, alpha, beta, emission_matrix):
        n_states = alpha.shape[0]
        T = alpha.shape[1]
        A_new = np.zeros((n_states, n_states))
        xi = np.zeros((n_states, n_states, T))
        for i in range(n_states):
            for j in range(n_states):
                for t in range(T - 1):
                    scaling_factor = emission_matrix[:, t].max()
                    #sannolikheten att få x_{t+1} men b_j
                    #here i use the scaling factor to get the true probability
                    xi[i, j ,t] = alpha[i, t] * self.stateGen.A[i, j] * emission_matrix[j][t+1] * scaling_factor * beta[j, t + 1]
        #get xi_{i,j}
        xi_sum = np.sum(xi, axis=2)
        print("xi_sum ", xi_sum.shape)
        for i in range(n_states):
            total_transitions_from_i = np.sum(xi_sum[i, :])  # Sum over all j for state i
            for j in range(n_states):
                A_new[i, j] = xi_sum[i, j] / total_transitions_from_i
        self.stateGen.A = A_new
            
